### ISSUE TITLE
Current online lesson pages are broken 

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/sql-ecology-lesson#102]
The current lesson page for this repo linked from the main Data Carpentry site are displaying like this:

![screenshot from 2016-08-29 09 10 06](https://cloud.githubusercontent.com/assets/744427/18052552/ffb9f67c-6dc8-11e6-9442-d7e7add4df61.png)

When I build the pages locally using Jekyll they work, but are filled with FIXME's.

Looks like this has been down for at least 3 days. Cc'ing @gvwilson since he was involved in the most recent changes.

**Comment by ethanwhite** [comment]
If I'm reading everything right it looks like there's a lot of code that's been pushed directly into the `gh-pages` branch without local review, possibly based on Software Carpentry's templating system?

Students in my university course are supposed to be reading this material today so any help getting this straightened out quickly would be appreciated.

**Comment by gvwilson** [comment]
On it.

**Comment by tpoisot** [comment]
My bad -- should we write a PR template to remind contributors to test locally?

**Comment by ethanwhite** [comment]
@tpoisot - are you intentionally moving over to SWC's template?

**Comment by ethanwhite** [comment]
@tpoisot - never mind. Incoming from @gvwilson will explain what happened and propose a fix.

**Comment by gvwilson** [comment]
This wasn't @tpoisot - this was me.  I updated to the new template to 
show @tracykteal what it would look like, but that was only supposed to 
show up in my repo, not this one.  If I reset to 8ed2ebb, everything 
should go back to where it's supposed to be, and the later commits are 
all related to the template change, so there's no loss in cutting them out.

**Comment by ethanwhite** [comment]
:+1:

**Comment by gvwilson** [comment]
"Cannot force-push to a protected branch."

**Comment by gvwilson** [comment]
~~~
$ git push --force origin gh-pages
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.
remote: error: Cannot force-push to a protected branch
To git@github.com:datacarpentry/sql-ecology-lesson.git
 ! [remote rejected] gh-pages -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'git@github.com:datacarpentry/sql-ecology-lesson.git'
~~~

**Comment by ethanwhite** [comment]
I have permissions to remove the protection (as do both of you probably) and am happy to do it if @tpoisot wants me to.

**Comment by ethanwhite** [comment]
I have temporarily implemented @gvwilson's proposed fix in my fork and forwarded those links along to my class, so the rush on my end has been dealt with. Let me know if there's anything I can do to help get things fixed up more generally.

**Comment by tpoisot** [comment]
Go ahead and force-push.

**Comment by ethanwhite** [comment]
OK, I just unprotected the branch. @gvwilson - fire away.

**Comment by gvwilson** [comment]
Thanks - pushed.  My apologies for the mistake.

**Comment by ethanwhite** [comment]
Thanks. I've re-protected the branch and added a push access restriction so that only @tpoisot, @orchid00, and admins can push to `gh-pages` in the hopes of avoiding similar accidents in the future. Thanks for helping get this sorted out quickly @gvwilson.

**Comment by orchid00** [comment]
Sorry I missed all the fun, this happened while I was asleep (different time zones). Glad to hear it all worked out. @ethanwhite if your students are reading the material, maybe you could suggest them to point out typos or any misunderstanding :)

**Comment by tpoisot** [comment]
@orchid00 great idea! Come on @ethanwhite , anyone that solves an issue gets extra credit.

**Comment by ethanwhite** [comment]
I'll see what I can do.
