### ISSUE TITLE
SQL aggregation "Null values" section: code blocks not formatted as code

### ISSUE THREAD

**Issue by brainwane** [datacarpentry/sql-ecology-lesson#105]
In the "null values" section of [the SQL Aggregation episode/page](http://www.datacarpentry.org/sql-ecology-lesson/02-sql-aggregation.html), we see:

But if we try to be extra clever, and find the average ourselves, we might get tripped up:

SELECT SUM(weight), COUNT(), SUM(weight)/COUNT() FROM summer_2000 WHERE species_id == ‘PE’

and the `SELECT` statement isn't formatted as a code block. This is because that `SELECT` statement -- like others on the same page -- isn't indented enough in the Markdown file. I'm fixing this with a pull request.

**Comment by orchid00** [comment]
approved the changes adding indentation.
