### ISSUE TITLE
SQLite plugin install

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/sql-ecology-lesson#108]
sqlSetup.html should include instructions for installing the SQLite plugin for Firefox.

**Comment by ErinBecker** [comment]
Install instructions are in 00-sql-introduction.html, but unclear if participants will go to lesson page before workshop. More likely to only view workshop home page.

**Comment by orchid00** [comment]
@ErinBecker maybe add a link to the first page? like here is how to install
