### ISSUE TITLE
Add mention of different JOIN types

### ISSUE THREAD

**Issue by mshelley1** [datacarpentry/sql-ecology-lesson#110]
In the lesson on joins, a brief mention of the existence of multiple types of join might be useful. If students try to apply JOIN to their own data and aren't aware that non-matching rows will be dropped, it could be frustrating. I would be happy to do a PR adding this caution to the end of "Joins" if desired.

**Comment by orchid00** [comment]
please add an short explanation about crossmatching, and possibly a bit on keys (primary  foreign)
