### ISSUE TITLE
Fix CONTRIBUTING in new template

### ISSUE THREAD

**Issue by ashander** [datacarpentry/sql-ecology-lesson#127]
remove/merge info from CONTRIBUTING_orig.md into CONTRIBUTING.md

**Comment by orchid00** [comment]
@ErinBecker Does this make any difference, the way it is?

**Comment by ashander** [comment]
currently new template has some FIXMEs in it, e.g https://github.com/datacarpentry/sql-ecology-lesson/blame/gh-pages/CONTRIBUTING.md#L49-L50

I'm going to fix this and will also see if there are changes from old CONTRIBUTING

**Comment by ashander** [comment]
the narrow issue is fixed in #158 

 a broader discussion of including old DC specific material can take place in #159
