### ISSUE TITLE
Format Key Points

### ISSUE THREAD

**Issue by ashander** [datacarpentry/sql-ecology-lesson#129]
These are not currently formatted in any of the episodes. If there are none, delete the box

- [x] 00-sql-introduction.md  
- [x] 01-sql-basic-queries.md  
- [x] 02-sql-aggregation.md  
- [x] 03-sql-joins-aliases.md

**Comment by orchid00** [comment]
Not so sure what the issue is

**Comment by tpoisot** [comment]
Me neither.

**Comment by ashander** [comment]
The new template has a 'Key Points' box at the end of each lesson. Currently these are empty, e.g. in Lesson 00

![image](https://cloud.githubusercontent.com/assets/510776/24106829/5f9249ec-0d46-11e7-94a2-1995689858e4.png)

**Comment by orchid00** [comment]
OK, this is likely to be part of the template. Would you like to add some key points as a PR?

**Comment by bsmith89** [comment]
I'll take this for `00-sql-introduction.md`.

**Comment by bsmith89** [comment]
For my own reference: key points are added to the YAML header of the `.md` file for the episode like so:

```
---
title: "Formatting"
teaching: 10
exercises: 0
questions:
- "How are Software and Data Carpentry lessons formatted?"
objectives:
- "Explain the header of each episode."
- "Explain the overall structure of each episode."
- "Explain why blockquotes are used to format parts of episodes."
- "Explain the use of code blocks in episodes."
keypoints:
- "Lesson episodes are stored in _episodes/dd-subject.md."
- "Each episode's title must include a title, time estimates, motivating questions, lesson objectives, and key points."
- "Episodes should not use sub-headings or HTML layout."
- "Code blocks can have the source, regular output, or error class."
- "Special sections are formatted as blockquotes that open with a level-2 header and close with a class identifier."
- "Special sections may be callouts or challenges; other styles are used by the template itself."
---
```

**Comment by ashander** [comment]
Helpful stuff for anyone else working on this too. Thanks!

**Comment by bsmith89** [comment]
It would appear that other DC lessons also don't have Key Points sections.  Is this something that should be changed?

**Comment by ashander** [comment]
There are probably existing issues/PRs flagging this in appropriate repos.

I know they're being added / have been added in at least one case:
https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/126

**Comment by ashander** [comment]
ps @bsmith89 please update here if you are taking this on for more than just lesson `00` (no pressure ;). if so I'll update the checklist above accordingly

**Comment by ASGeorge** [comment]
Good day. Working on adding key points for 01-sql-basic-queries.md.

**Comment by bsmith89** [comment]
Will do.

Also, again for my own reference (sorry if this is getting spammy), here is an example from swcarpentry/python-novice-gapminder Episode 7:

```
keypoints:
- "Use the Pandas library to do statistics on tabular data."
- "Use `index_col` to specify that a column's values should be used as row headings."
- "Use `DataFrame.info` to find out more about a dataframe."
- "The `DataFrame.columns` variable stores information about the dataframe's columns."
- "Use `DataFrame.T` to transpose a dataframe."
- "Use `DataFrame.describe` to get summary statistics about data."
```

**Comment by bsmith89** [comment]
Releasing `00-sql-introduction.md`.

Claiming `02-sql-aggregation.md`.

**Comment by bsmith89** [comment]
Done (for now) contributing to `02-sql-aggregation.md`.

**Comment by ashander** [comment]
I'll add some for `03-sql-joins-aliases/`

**Comment by bsmith89** [comment]
The choice of key points look really good (IMO) in #157, #161, #162, and #165.

One thing maybe worth considering is that the voice we've used is inconsistent across the four episodes.  This is also the case across Carpentries lessons, e.g. [SWC-shell-episode2](http://swcarpentry.github.io/shell-novice/02-filedir) vs. [SWC-python-gapminder-episode7](http://swcarpentry.github.io/python-novice-gapminder/07-reading-tabular/)

Is it worth thinking about a "style guide" for these key points, either within this lesson or more globally?

**Comment by ashander** [comment]
good point @bsmith89 I'm not sure we could or should take on the broader issue here, but it's good to flag it. for the issue of consistency across our PRs, what specifically do you mean? I've merged everything and pasted a combined diff below for easy reference. Differences I see:

- some of the points are pithier and some more verbose. (I'd favor pithier while possible)
- use of ` `` ` around commands/keywords


#### _episodes/00-sql-introduction.md:
<details>

```sh
index bab2d21..bdb3a35 100644
--- a/_episodes/00-sql-introduction.md
+++ b/_episodes/00-sql-introduction.md
@@ -8,6 +8,10 @@ questions:
 objectives:
 - "Understand the benefits of using a relational database"
 - "Set up a small database using SQLite"
+keypoints:
+- "SQL allows us to select and group subsets of data, do math and other calculations, and combine data."
+- "A relational database is made up of tables which are related to each other by shared keys."
+- "Different database management systems (DBMS) use slightly different vocabulary, but they are all based on the same ideas."
 ---
 
 ## Learning Objectives
```
</details>


#### _episodes/01-sql-basic-queries.md:
<details>

```sh
index 9be5b23..0034ace 100644
--- a/_episodes/01-sql-basic-queries.md
+++ b/_episodes/01-sql-basic-queries.md
@@ -8,6 +8,11 @@ objectives:
 - "Write and build queries."
 - "Filter data given various criteria."
 - "Sort the results of a query."
+keypoints:
+- "It is useful to apply conventions when writing SQL queries to aid readability."
+- "Use logical connectors such as AND or OR to create more complex queries."
+- "Calculations using mathematical symbols can also be performed on SQL queries."
+- "Adding comments in SQL helps keep complex queries understandable."
 ---
 
 ## Learning objectives
```
</details>


#### _episodes/02-sql-aggregation.md:
<details>

```sh
index 2a5d039..c3514be 100644
--- a/_episodes/02-sql-aggregation.md
+++ b/_episodes/02-sql-aggregation.md
@@ -9,6 +9,11 @@ objectives:
 - "Filter and order results of a query based on aggregate functions."
 - "Save a query to make a new table."
 - "Apply filters to find missing values in SQL."
+keypoints:
+- "Use the `GROUP BY` keyword to aggregate data."
+- "Functions like `MIN`, `MAX`, `AVERAGE`, `SUM`, `COUNT`, etc. operate on aggregated data."
+- "Use the `HAVING` keyword to filter on aggregate properties."
+- "Use a `VIEW` to save a query as though it were a new table."
 ---
 
 ## Learning Objectives
```
</details>


####  _episodes/03-sql-joins-aliases.md:
<details>

```sh
index 34b2c45..29a6368 100644
--- a/_episodes/03-sql-joins-aliases.md
+++ b/_episodes/03-sql-joins-aliases.md
@@ -8,6 +8,13 @@ objectives:
 - "Employ joins to combine data from two tables."
 - "Apply functions to manipulate individual values."
 - "Employ aliases to assign new names to items in a query."
+keypoints:
+- "Use the `JOIN` command and `ON` or `USING` keywords to combine data from two tables."
+- "Regular `JOIN` returns only matching rows. Other join commands provide different behavior, e.g., `LEFT JOIN` retains all rows of the table on the left side of the command."
+- "`IFNULL` allows you to specify a value to use in place of `NULL`, which can help in joins"
+- "`NULLIF` can be used to replace certain values with `NULL` in results"
+- "Many other functions like `IFNULL` and `NULLIF` can operate on individual values."
+- "Aliases can help shorten long queries. To write clear and readible queries, use the `AS` keyword when creating aliases."
 ---
 
 ## Learning Objectives
```

</details>

**Comment by bsmith89** [comment]
-  pithier vs. verbose is the most obvious one
-  choices about at what level details should be combined into a single point versus split up
-  scope of key-points: should they be limited to details of using SQL, or does conceptual stuff belong, too.

**Comment by tracykteal** [comment]
Thanks for the idea of the style guide for 'key points'. This is a good broader discussion. I created an issue in the lesson templates repository. https://github.com/swcarpentry/lesson-example/issues/112
