### ISSUE TITLE
Setup link broken in 00-sql-intro

### ISSUE THREAD

**Issue by ashander** [datacarpentry/sql-ecology-lesson#130]
https://github.com/datacarpentry/sql-ecology-lesson/blame/c3138e892504e041ea05021b6ddd851bb8bbd0c7/_episodes/00-sql-introduction.md#L24

**Comment by tpoisot** [comment]
Can you please submit a PR?

**Comment by ashander** [comment]
I'm not sure what the link should be. Possibly reopen so someone who knows can fix it?

**Comment by orchid00** [comment]
In the page https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/_episodes/00-sql-introduction.md
Setup should link to http://www.datacarpentry.org/sql-ecology-lesson/setup/

@ashander Do you want to create the PR?
