### ISSUE TITLE
check for clarity and flow of narrative [Lesson release checklist] 

### ISSUE THREAD

**Issue by sarahsupp** [datacarpentry/sql-ecology-lesson#133]
in: 00-sql-introduction.md

The definition below could specify that records (rows) and fields (columns). This is not necessarily obvious to a complete [novice.]

    Definition: Relational database

    A relational database is a digital database where all data is stored in relations (or tables) containing rows and columns. All tables contain records and all records are identified by a field contiaing a unique value. Every table shares at least one field with another table in one-to-one, one-to-many or many-to-many relationships. This allows the user to access the data in many ways {: .callout}

**Comment by sarahsupp** [comment]
in 00-sql-introduction.md

The instructions here don't say where students can find the portal_mammals.sqlite file, and they don't provide a link. It also isn't clear how the file should be opened. Specify if "open file" is in RStudio or something else.

Let's download and look at a pre-existing database, the portal_mammals.sqlite file. Clicking on the "open file" icon and then that file will open the database.

**Comment by sarahsupp** [comment]
in all SQL lessons:

The box for "Key Points" at the end of the page is blank. Should this be filled in, or is it just to remind the instructor to do a quick review and check-in with students?

**Comment by ashander** [comment]
- [ ] 00
- [ ] 01
- [ ] 02
- [ ] 03

I'll do the fixes in  00-sql-introduction.md, I don't think any issues with flow were pointed out in any other of the lessons

**Comment by ashander** [comment]
The definition issue was addressed in https://github.com/datacarpentry/sql-ecology-lesson/pull/149

**Comment by tracykteal** [comment]
This has been updated and clarity and flow is much better
