### ISSUE TITLE
check that the learning objectives reflect the content of the lessons [Lesson Release checklist]

### ISSUE THREAD

**Issue by sarahsupp** [datacarpentry/sql-ecology-lesson#134]
in: 00-sql-introduction.md

The learning objectives listed at the top of this lesson are not all covered in this .md file and they are not in the same order as encountered in the lesson. 

They should either match the 2 objectives given in the header, or be trimmed to the 3 that are covered:
-     Describe why relational databases are useful.
-     Define SQLite data types.
-     Create and populate a database from a text file.

> Learning Objectives

    Create and populate a database from a text file.
    Describe why relational databases are useful.
    Define SQLite data types.
    Select, group, add to, and analyze subsets of data.
    Combine data across multiple tables.

**Comment by sarahsupp** [comment]
in: 01-sql-basic-queries.md

The question in the header is not phrased as a question. Suggest:

How do I write a basic query in SQL?

> Learning Basic Queries in SQL

**Comment by sarahsupp** [comment]
in all SQL lessons: 

The box for "Key Points" at the end of the page is blank. Should this be filled in, or is it just to remind the instructor to do a quick review and check-in with students?

**Comment by sarahsupp** [comment]
in: 01-sql-basic-queries.md

Students learn more than just filtering and sorting data. A learning objective could be added to calculate new values based on data/fields. 

Also, the first learning objective could be more specific:
Write and build queries**, from simple to increasing complexity.**

**Comment by sarahsupp** [comment]
02-sql-aggregation.md

The question in the header is not phrased as a question. Suggest:

How can I summarize my results through aggregating, filtering, or ordering the data?

>  Aggregating, filtering and ordering query results

**Comment by sarahsupp** [comment]
in: 03-sql-joins-aliases.md

The question in the header is not phrased as a question. Suggest multiple questions to be listed:

How do I bring data together from separate tables?
How can I make sure column names from my queries make sense and aren't too long?

>     Joining tables and creating aliases

**Comment by ashander** [comment]
This relates to #132

**Comment by orchid00** [comment]
@sarahsupp could you please put small changes as PR. In the future issues should have one topic this makes it easier to solve.

**Comment by ashander** [comment]
As mentioned in https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/78 this is issue across all DC. Discussion should take place at linked issue, and decision reached there should be implemented here too.

Choice is to harmonize them to be the same or merge them to only be in Overview.

**Comment by ashander** [comment]
My understanding of the upshot of discussion on other issues: only state these once, in the yaml frontmatter under 'objectives'. I will make the fix
