### ISSUE TITLE
Lesson 00 should include importing surveys

### ISSUE THREAD

**Issue by ashander** [datacarpentry/sql-ecology-lesson#136]
as lesson 01 begins with using `surveys`

this could be in the 'challenge' or in a demo before the challenge, but should be done explicitly

**Comment by orchid00** [comment]
There is an import section in https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/_episodes/00-sql-introduction.md

Would you like to add something extra?

**Comment by ashander** [comment]
There is explicit reference (in challenges) to 

`Import the plots and species tables {: .challenge}`

but no reference to importing `surveys` anywhere.

Options:

- add it to the challenge
-  the text around `## Import` should make clear that `surveys` is to be used a demo by the intructor.

**Comment by orchid00** [comment]
I see it in 
Select the file to import
Give the table a name that matches the file name (surveys, species, plots)

Again, Would you like to add something extra?

**Comment by ashander** [comment]
I will work on this. Going to add language explicitly saying to import surveys
