### ISSUE TITLE
confusing definition of relational database?

### ISSUE THREAD

**Issue by njamescouk** [datacarpentry/sql-ecology-lesson#140]
http://www.datacarpentry.org/sql-ecology-lesson/00-sql-introduction/

"database where all data is stored in relations (or tables) containing rows and columns"

perhaps 
"data is stored in tables which have a fixed number of columns and variable number of rows. Rows in different tables may be related to each other by assigning the same identifier to corresponding rows."

 would be better?

needs a picture really

**Comment by orchid00** [comment]
Less open this for discussion:
A relational database is a digital database where all data is stored in tables which have a fixed number of columns and a variable number of rows. All tables contain records and all records are identified by a field containing a unique value. Every table shares at least one field with another table in a one-to-one, one-to-many or many-to-many relationship. This allows the user to access the data in many ways.

The second part of your suggestion goes in the second part of the concept provided. 
How does it sound to you? 
For a picture, you are welcome to offer a suggestion.

**Comment by njamescouk** [comment]
image of db structure: https://www.dropbox.com/s/bwgqujlm7se0a6v/portal_mammals_relations.png?dl=0

**Comment by maneesha** [comment]
@njamescouk - Good way of showing how tables relate to each other.  I would make the column widths for name and type consistent down each set of rows.

**Comment by njamescouk** [comment]
@maneesha @gvwilson thinks diagram inadequate so will let this drop. It's produced mechanically and process can't really be adapted as required :-(

**Comment by ashander** [comment]
Looks like this will be closed if #149 is merged
