### ISSUE TITLE
http://www.datacarpentry.org/sql-ecology-lesson/03-sql-joins-aliases/

### ISSUE THREAD

**Issue by njamescouk** [datacarpentry/sql-ecology-lesson#143]
Aliases para

 second example doesn't seem to use aliases, last three lines identical in both cases, note on AS doesn't relate to second example.

sql in solutions ok, but no semi colons

**Comment by orchid00** [comment]
as before, please open a PR

**Comment by maneesha** [comment]
@njamescouk  Can you share more specifically what examples you're referring to?  It looks like the 'Aliases' section includes using aliases to get column names and how `AS` is not necessary.

**Comment by maneesha** [comment]
PR https://github.com/datacarpentry/sql-ecology-lesson/pull/151 addresses the semicolons

**Comment by njamescouk** [comment]
I was looking at an out of date repo or this has been rewritten since I commented, I can't see any error,
