### ISSUE TITLE
minor formatting nit pick

### ISSUE THREAD

**Issue by njamescouk** [datacarpentry/sql-ecology-lesson#145]
https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/_episodes/03-sql-joins-aliases.md

SELECT COUNT(*) FROM surveys;

should perhaps read 
SELECT COUNT(*) 
FROM surveys;

**Comment by orchid00** [comment]
can you make a Pull Request? please

**Comment by tpoisot** [comment]
Closing -- reopen as PR.
