### ISSUE TITLE
Broken Link in lessons page

### ISSUE THREAD

**Issue by gvdr** [datacarpentry/sql-ecology-lesson#146]
I think that the link in this page http://www.datacarpentry.org/lessons/ to the Instructor Guide is broken.

Currently is https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/instructor-notes.md

Should be https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/_extras/guide.md

:-)

**Comment by ashander** [comment]
Fixed in above PR to main website
