### ISSUE TITLE
Missing summary on SQL Aggregation module

### ISSUE THREAD

**Issue by kariljordan** [datacarpentry/sql-ecology-lesson#182]
The [SQL Aggregation](http://www.datacarpentry.org/sql-ecology-lesson/02-sql-aggregation/) module ends abruptly. Should there be more text after the query? This is how the module ends:

There is one more subtlety we need to be aware of. Suppose we run this query:
SELECT COUNT(*), weight
FROM summer_2000;

    Key Points
        Use the GROUP BY keyword to aggregate data.
        Functions like MIN, MAX, AVERAGE, SUM, COUNT, etc. operate on aggregated data.
        Use the HAVING keyword to filter on aggregate properties.
        Use a VIEW to access the result of a query as though it was a new table.

Seems like there should be a sentence or two after the query text and before the key points.

**Comment by orchid00** [comment]
@kariljordan  would you like to suggest a sentence to add. you could do this as a PR.

**Comment by kariljordan** [comment]
Hi @orchid00, I'm going to tweet this issue because I honestly don't have a lot of experience with SQL.

**Comment by tracykteal** [comment]
It seems like everything below "But if we try to be extra clever, and find the average ourselves, we might get tripped up:" isn't really about saving views. Instead it is about how SQL handles NULL values and some of the subtleties. 

Should we include this discussion of NULL values? If so, maybe we should at least break it out into its own section and complete it. 

I also see that in this PR, we lost an exercise. https://github.com/datacarpentry/sql-ecology-lesson/commit/f02e01765c3f8844e0f53782874b13cb7ea0e1bd

I think that is a useful exercise, and it also separates out the sections, so I'll put in a PR to put a version of that exercise back in.

**Comment by tracykteal** [comment]
Ah, ha! In that PR, it also lost the Null values header, so that makes more sense. I'll put the header back too.

**Comment by tracykteal** [comment]
Actually, that whole PR changes the intent of the Null section. Sorry, I merged that PR, so should have done a better review. What do we think about going back to the having a 'View' exercise and a section on Null values? So, we could incorporate some of those changes, but just not all.

**Comment by kariljordan** [comment]
@tracykteal I think that is a great idea (section on View and section on Null) because they are both important topics and distinct. I'm pulling @tpoisot in to this conversation since he's the other maintainer. Yippee!

**Comment by amyehodge** [comment]
Please see my mention that placement of NULL introduction should also consider the IFNULL etc functions discussed in the FUNCTION section.

**Comment by orchid00** [comment]
Thanks for this discussion. In order to move forward, as maintainer I have decided to remove that extra sentence and example. The episode is much clearer with out it. If any of you would like to offer a complete PR to add some information about it, I will welcome that.
