### ISSUE TITLE
Remove AS from before it is taught

### ISSUE THREAD

**Issue by AlfAWolf140** [datacarpentry/sql-ecology-lesson#183]
When I was teaching the lesson earlier I noticed that AS is used in the IFNULL and NULLIF sections before it's taught in the ALIAS section. This meant that I ended up explaining it twice. I don't know which would be the better option, but I'd like to suggest either:

a) Remove the AS statements from the following
SELECT species_id, plot_id, NULLIF(plot_id, 7) AS partial_plot_id
FROM surveys;

SELECT species_id, sex, IFNULL(sex, 'U') AS non_null_sex
FROM surveys;

b) Move the alias section above the IFNULL and NULLIF sections

**Comment by ChristinaLK** [comment]
I saw the same thing when I taught this last week.

**Comment by orchid00** [comment]
Option a) seems sensitive. Thanks for pointing it out @AlfAWolf140 and @ChristinaLK. I have updated it.

**Comment by orchid00** [comment]
I fixed this! Aliases is now on episode 2! 
(finally!)
