### ISSUE TITLE
rework some challenges?

### ISSUE THREAD

**Issue by ChristinaLK** [datacarpentry/sql-ecology-lesson#184]
Right now the exercises are written in a way that makes it easy to translate into SQL queries.  Some of them could be re-written so that participants have to think more carefully about which pieces of the question translate into query language.  

For example, from the section on filtering with WHERE, the current challenge is: 
> Write a query that returns the day, month, year, species_id, and weight (in kg) for individuals caught on Plot 1 that weigh more than 75 g

I rewrote that as: 
> Produce a table listing the data for all individuals in Plot 1 that weighed more than 75 grams, telling us the date, species id code, and weight. 

I also tried to frame the challenges as ways to find the answer to a research question, which people seemed to appreciate.

**Comment by orchid00** [comment]
@ChristinaLK great work rephrasing the challenges. Have you sent a PR? I haven't seen it. If you did then let me know if I can close this issue or if you need more feedback.

**Comment by ChristinaLK** [comment]
I haven't yet, but I'll add it to my list of things to do.  :)

**Comment by orchid00** [comment]
Thanks, @ChristinaLK I have updated this specific challenge in 01-sql-basic-queries.md with your suggestion. I will keep this issue open until I hear back from you and maybe some PR.
No rush, just letting you know that the BBQ is August 3, 4 if you would like to work on that.
All the best!
