### ISSUE TITLE
SQLite Manager Firefox plugin does not create files

### ISSUE THREAD

**Issue by exsilica** [datacarpentry/sql-ecology-lesson#185]
An instructor - @henrykironde - and I have noticed that we need to work in between the SQLite Manager desktop application and Firefox plugin. The plugin on its own does not create new databases, but does open existing .sqlite files. Are there Firefox settings we can adjust to give the plugin permissions to write files?

(I have not been trained as a DC instructor so I apologize if I am missing some details.)

**Comment by orchid00** [comment]
hi @exsilica, could you please check with a newer version of Firefox? or maybe ask others with different settings or OS. I am not aware of others having this issue.
