### ISSUE TITLE
SQL Aggregation Aliases

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/sql-ecology-lesson#189]
Submitted by email for Instructor Training checkout.

What: Add a note about GROUP BY and ORDER BY statements- you can substitute the number of the order a column appears in the select statement with the name of the column in a GROUP BY statement. For example the following query would change from

SELECT species_id, COUNT(*)
FROM surveys
GROUP BY species_id;

to

SELECT species_id, COUNT(*)
FROM surveys
GROUP BY 1;

and produce identical results.

Where: Add this directly after the introduction of the concept of Aliases and show that the above queries will produce the same results with a brief callback to the previous section. 

Why:
-Pros to using this approach are that it makes writing the query much quicker especially if you are grouping all of the selected columns in a specific order or if you have a lot of selected columns in general. It is also easier to go back and edit should you need to.

-Cons to using this approach are that it may be confusing or ambiguous to someone who is using/reading the code, but did not write it.

-Advise: Only use this trick when writing one-off queries that will not necessarily be reviewed by others

What to remove: The "AS isn't required" sample query can easily be replaced with this query. You could even just not use the "AS" in the query that explains the numbering as a catch-all for both explanations

NOTE: If this method was implemented earlier in the lesson like at the "Sorting" section or the "COUNT and GROUP BY" section and used afterward, the time used to explain it would be made up by the speed at which the instructor could write the remaining queries.

Estimated time added: 3 min (without removing anything)

**Comment by orchid00** [comment]
As it is referenced in #190 First we need to decide what to do with the Aliases part, now section 02 is using it but it is only explained later in section 03. On one hand, If we want to add this concept it will fit better in section 02, in my opinion. On the other hand, I don't think this addition is something necessary for novices to learn. Any other thoughts?

**Comment by tpoisot** [comment]
I'm not sure mentioning this is useful. You can rename columns and use their names, so the query looks more like english. Using numbers makes the query code much harder to maintain.

**Comment by orchid00** [comment]
Thanks @tpoisot I agree with you and would also suggest not to implement this update. I will close this issue.
