### ISSUE TITLE
portal_mammals.sqlite has incorrect column types

### ISSUE THREAD

**Issue by remram44** [datacarpentry/sql-ecology-lesson#202]
When running from the included `portal_mammals.sqlite` file instead of recreating it, you will run into an issue running some queries because the data type are wrong (compared to what's listed in the lesson). For instance, the `weight` is INTEGER instead of REAL, which means that `SELECT weight/1000` will give out all 0 instead of the expected decimal values (you can do `weight/1000.0`, but explaining why to students is very awkward).

I can make a fixed version of the `.sqlite` file, but since this is on figshare I can't replace it [edit: found the upstream github]

**Comment by ethanwhite** [comment]
From a data structure perspective these data are actually integers as they are only collected to the nearest gram/millimeter. This is why they are explicitly cast into integers in the creation of the database:

https://github.com/weecology/portal-teachingdb/blob/master/create_portal_teaching_dataset.py#L59

SQLite uses integer division on integers which is what produces this result. When I teach this material I typically show it using `1000.0` and then wait until someone (inevitably) does it using `1000` and asks and then I explain what's going on with integer division.

That said, I can see the pedagogical argument for just avoiding this in the first place by casting the integer data as real. This might result in some questions about why the integers are defined as reals, but that would probably be infrequent.

Does anyone else have thoughts on what the ideal choice is pedagogically here? If there is general agreement that avoiding integer division issues is the right way to go I can update the version of the database on figshare.

**Comment by remram44** [comment]
I don't really have a problem either way, my issue was that the first time I ran through the lesson, I created the database from the CSV file as described, and the lesson says to import those columns as REAL ([here](http://www.datacarpentry.org/sql-ecology-lesson/00-sql-introduction/#import)). I was surprised the `.sqlite` file was different, I think that's my real issue.

**Comment by ethanwhite** [comment]
Ah, got it, that's something that's changed since I wrote the lesson and built the dataset, and I totally agree that they should be consistent. Let's see what the current maintainers (and anyone else with thoughts) wants to do and then we can update either the data or the lesson to make sure that both match.

**Comment by ethanwhite** [comment]
Pinging @orchid00 & @tpoisot for their take on this. I'm personally leaning towards @remram44's suggested change to make the pre-built database inline with the types described in the lesson and avoid the pedagogical stumbling block of integer division.

**Comment by ethanwhite** [comment]
Since this has been sitting for a few months I think we should go ahead and make the change suggested by @remram44. I'm going to go ahead and get https://github.com/weecology/portal-teachingdb/pull/5 cleaned up and merged and the sqlite file updated.

**Comment by ethanwhite** [comment]
I've merged weecology/portal-teachingdb#5 and updated the file on figshare. Since it doesn't look like that file is hard-linked anywhere (just the top level DOI) this should be all fixed. Thanks again reporting this issue and the discussion to figure out the best way forward @remram44!

**Comment by remram44** [comment]
Thanks @ethanwhite! The setup page links to `http://dx.doi.org/10.6084/m9.figshare.1314459`, is that updated?

**Comment by ethanwhite** [comment]
It is updated and the data types read as `Numeric`, but I see the same behavior. This suggests that https://github.com/weecology/portal-teachingdb/pull/5 didn't end up solving the issue. @remram44 if you have some time to explore this I'd be happy to get another fix in and the data updated again.

**Comment by remram44** [comment]
Indeed my patch doesn't work :pensive: Apologies! It is possible that this is version dependent, or I just messed up during testing. weecology/portal-teachingdb#7 is a tiny change that should fix it.

**Comment by ethanwhite** [comment]
Thanks @remram44. No problem at all, that's definitely a confusing one. I've merged your PR, rebuilt the sqlite file, and replaced it on figshare. I downloaded it from figshare at the link above and tested it. The integer division looks like it's gone to me. Thanks again for bringing this up and for all the work on the fixes.
