### ISSUE TITLE
The first challenge does not have a solution provided 

### ISSUE THREAD

**Issue by kylemonahan** [datacarpentry/sql-ecology-lesson#205]
The first challenge doesn't provide a solution, and might be hard for some students to complete. 

"Write a query that returns The year, month, day, species_id and weight in mg" 

We can add a query as the following in a dropdown:

```
SELECT year, month, day, species_id weight/1000
FROM surveys;
```
We can also remind them of the semicolon issue, since they only saw it twice before: once during this lesson, and once conceptually in the previous lesson [here](http://www.datacarpentry.org/sql-ecology-lesson/00-sql-introduction/).

Happy to submit a pull request if you prefer.

**Comment by remram44** [comment]
Hi @kylemonahan! Indeed solutions need to be added for all the challenges. We already have solutions sitting in PR #187 and #204, currently waiting for review, so I don't think we need more patches right now.

There has been some changes in the maintainer team, and hopefully we can get those PRs merged soon.

**Comment by kylemonahan** [comment]
Thanks for getting back to me so quickly! I'll check out those solutions. Happy to help where I can!
