### ISSUE TITLE
Question about Challenge in "COUNT and GROUP BY" section

### ISSUE THREAD

**Issue by mkweskin** [datacarpentry/sql-ecology-lesson#210]
Could you clarify the final part of this challenge in the "COUNT and GROUP BY" section:

```
Write queries that return:

1. How many individuals were counted in each year
    - in total
    - per each species
2. Average weight of each species in each year.
Can you modify the above queries combining them into one?
```

Is the final part asking you to combine three queries? Two in part 1: counts by year, counts by year & species, plus one in part 2: average weight by year? I don't think the intention is to have people combine the two types of grouping in part 1 into a query, just to report counts and average weight by year weight in one query.

A clarification might be:
```
Write queries that return:

1. How many individuals were counted in each year
2. Average weight of each species in each year.
Can you modify the above queries combining them into one?
Can you modify the queries to report per each species in each year?
```

**Comment by remram44** [comment]
Hmm something is definitely unclear here, thank you for pointing it out!

I'm not sure your correction works though, because you can't really get the average weight per species and the number of individuals NOT per species.

Maybe something like this, referring to numbers explicitly:
```
1. How many individuals were counted in each year in total
2. How many individuals were counted in each year, for each species
3. The average weights of each species in each year

Can you get the answer to both 2 and 3 in a single query?
```

**Comment by mkweskin** [comment]
Yes, I think your suggested rewording works well!
