### ISSUE TITLE
Import of NULL from CSV in DB Browser for SQLite

### ISSUE THREAD

**Issue by mkweskin** [datacarpentry/sql-ecology-lesson#211]
I noticed that "DB Browser for SQLite" handles import of missing values from CSVs differently than the old Firefox "SQLite Manager."

In "DB Browser for SQLite" missing values in a csv are not imported as NULL in the database, rather they are given no value (but aren't NULL). In the Firefox "SQLite Manager" those missing values are given NULL. The result is that you don't end up with any NULL values which messes with the parts of the lesson where you cover NULL.

I haven't figured out to change the import behavior of "DB Browser for SQLite", probably a question for that project.

**Comment by mkweskin** [comment]
Using import in the new system gives you a database with no NULL values. In the old system every missing value in the csv was treated as NULL.

For example, this query is from the old system:

```
SELECT COUNT(*) FROM surveys WHERE weight IS NULL;
3266
```

And this is the new one:

```
SELECT count(*) FROM surveys WHERE weight IS NULL;
0
```

I've added a feature request to sqlitebrowser: https://github.com/sqlitebrowser/sqlitebrowser/issues/1339

**Comment by remram44** [comment]
Indeed empty cells are imported as `""`. It might be good to have an option to import as `NULL` or `DEFAULT` but this seems to also be what sqlite3's `.import` command does.

**Comment by remram44** [comment]
It might also be good to add a comment to `00-sql-introduction` (though nothing is currently mentioned about missing values).

**Comment by mkweskin** [comment]
With the missing values being handled as TEXT `""` rather than NULL, the AVG() operation treats the `""` as 0 and they're included in the average.

When I taught SQL for Ecology last week using "DB Browser for SQLite" I used this difference as a way to demonstrate in the *SQL Aggregation and aliases* lesson that `""` is different from NULL. My co-instructors and I came up with having the participants use `UPDATE surveys SET weight = NULL WHERE weight = ""` to change the blanks to NULL to show the difference in AVG(). It wasn't my favorite to introduce `UPDATE`, but it seemed important so participants know how to handle something like this and to get AVG() working.

I'm not sure of the best suggestion for modifying the lesson content. I don't think adding the `UPDATE` is the best way to go.

**Comment by aelfric** [comment]
We're also trying to migrate from Firefox to DB Browser and this difference bit us unexpectedly.  I'd vote for an option to treat blanks as `NULL` on the import screen.

**Comment by remram44** [comment]
FYI I sent sqlitebrowser a pull request: sqlitebrowser/sqlitebrowser#1349

**Comment by mkweskin** [comment]
Quite amazing that you did that! That's real commitment to DC 😄

**Comment by justinclift** [comment]
As a follow up thing, the code to make this work better, as submitted by @remram44 was merged into DB Browser for SQLite (DB4S) a few days ago:

So, now it's in our automatically generated nightly builds:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org

There's a sub-directory on that server for each OS:

* https://nightlies.sqlitebrowser.org/win32/
* https://nightlies.sqlitebrowser.org/win64/
* https://nightlies.sqlitebrowser.org/osx/

Or just use the "latest" subdirectory, which gets a copy of the latest one for each OS each night.

* https://nightlies.sqlitebrowser.org/latest/

Our next "official" release (3.11.0) should be in a few weeks too.

Hope that helps. :smile:
