### ISSUE TITLE
creating and populating a database using the GUI

### ISSUE THREAD

**Issue by neausda** [datacarpentry/sql-ecology-lesson#225]
Start a New Database

    Database -> New Database
    Give a name Ok -> Open. Creates the database in the opened folder -HERE THE USER CAN CLOSE THE DATABASE AND THEN DOUBLE CLICK ON WHERE THEY SAVED IT

Start the import Database -> Import - HERE - IT IS FILE -> IMPORT
Select the surveys.csv file to import
Sincerely,

Jonathan Shao

**Comment by remram44** [comment]
Hi @neausda! I don't understand what you are trying to say. Is there an issue somewhere?
