### ISSUE TITLE
Objective list in Databases using SQL lesson

### ISSUE THREAD

**Issue by kyeater** [datacarpentry/sql-ecology-lesson#226]
The 4th Objective states that we will Select, Group, add to, and analyze....I don't think this is being accomplished in this lesson.  The Select and Group and add to really happens in the second Lesson of this series where Basic Queries in SQL is introduced.  There is no real analysis happening in this lesson. Thanks.

**Comment by remram44** [comment]
Hi @kyeater and thanks for the feedback! The idea is to give users the tools to do the queries they need to do on their data, doing an analysis on what the results mean is somewhat out of scope.

Do you have any concrete steps that would improve the analysis part presented in the lesson? Do you think we should be trying to answer more meaningful questions about the data?

**Comment by kyeater** [comment]
I think I have a different working definition of "analyze"; when I use that word in relationship to some data, I am thinking about applying a statistical method to summarize and/or begin to make inference about a question. It could be descriptive in nature, like calculating means, ranges, variances, etc., but that is an "analysis" - so that is why I suggest not including that wording choice in the objective.

**Comment by remram44** [comment]
I don't think "analysis" is an inherently statistical term. Also note that episode 02 does compute averages, sums, and ranges over the data or subsets of it.

**Comment by ChristinaLK** [comment]
out of date (I think)
