### ISSUE TITLE
"Getting Started" block and "Setup" page are almost a repetition of each other

### ISSUE THREAD

**Issue by steltenpower** [datacarpentry/sql-ecology-lesson#229]
In many situations people like the Don't-Repeat-Yourself (DRY) principle and I miss it in:
"Getting Started" block and "Setup" page are almost a repetition of each other
Are there any (template) rules to take into account before I suggest changes to both "Getting Started" block and "Setup" page? Is this "Setup" page linked to from other than this lesson overview page?

**Comment by steltenpower** [comment]
http://www.datacarpentry.org/sql-ecology-lesson/setup/ is visually off too

**Comment by remram44** [comment]
I don't think there is so much repetition between the too. You are welcome to propose improvements to those pages, though you might want to wait for #232 to be merged (fixing the display issue for the setup page).

**Comment by ChristinaLK** [comment]
I think this has been resolved in later PRs or reorganization.
