### ISSUE TITLE
highlight part of the query to focus on ?

### ISSUE THREAD

**Issue by steltenpower** [datacarpentry/sql-ecology-lesson#231]
For example: Where you're learning about LIMIT, highlight that line of the query?

**Comment by remram44** [comment]
Hi @steltenpower, this is probably a good idea, however I am not sure how to do that in markdown. I don't think you can use e.g. bold within a code block.

**Comment by ChristinaLK** [comment]
This would now be a `styles` question. @fmichonneau is this worth pursuing for the lessons in general, or should I just close the issue?

**Comment by fmichonneau** [comment]
I'm going to transfer this issue to the styles repo. I don't think it's something we can address in the short term, but might be worth exploring in the future.

**Comment by fmichonneau** [comment]
closing in favor of https://github.com/carpentries/styles/issues/492

(we can't transfer issues across organizations...)
