### ISSUE TITLE
Import Section - Directions outdated

### ISSUE THREAD

**Issue by jeremywalter** [datacarpentry/sql-ecology-lesson#238]
The current version of DB SQLite doesn't have the tabs or organization described in the module. As a novice, without being able to actually follow the instructions, it's unclear what the purpose of the instructions are.

**Comment by remram44** [comment]
Hi @vindie13,

Are you referring to [this section of the introduction](https://datacarpentry.org/sql-ecology-lesson/00-sql-introduction/#import)? Indeed this might need updating after our switch to DB4S.

Thanks for pointing it out!

**Comment by amyehodge** [comment]
I started reviewing this lesson today and am working on the PR to make all the necessary fixes.

**Comment by amyehodge** [comment]
I just submitted PR #241 for this.
