### ISSUE TITLE
View menu question in "SQL Aggregation and aliases"

### ISSUE THREAD

**Issue by kglibrarian** [datacarpentry/sql-ecology-lesson#244]
I had some confusion when reviewing the "SQL Aggregation and aliases" lesson, in particular the "Saving Queries for Future Use" section of the course: 

_"You can also add a view using Create View in the View menu and see the results in the Views tab, the same way as creating a table from the menu."_

I'm not very familiar with DB Browser for SQLite, but my "View" menu doesn't have "Create View" in it - instead it lists: "SQL Log, Plot, DB Schema, Edit Database Cell, Remote, DB Toolbar". If the "View" menu refers to the "Views" section in the "Database Structure" tab, then I was unable to see any option to "create view". Again, I'm not familiar with DB Browser for SQLite, so I may just be missing something. 

Thanks!

**Comment by remram44** [comment]
We have probably just missed those instructions from the old Firefox plugin. We'll need to update them for db4s.

https://github.com/datacarpentry/sql-ecology-lesson/blob/0cd347da74fb362fd204e68fc65a66649bf09121/_episodes/02-sql-aggregation.md#L209
