### ISSUE TITLE
Import does not work correctly with current release DBBrowser

### ISSUE THREAD

**Issue by henrykironde** [datacarpentry/sql-ecology-lesson#245]
@amyehodge noted that Import on the current  DBBrowser does not work as expected.
I have tested the issue with @fmichonneau and we found that the current stable version of DBBrowser
does not import data correctly.
However,  the nightly builds has the import function working as expected.
I have requested the folks at sqlitebrowser to release a new stable version. This will be resolved after the release
 

reference: https://github.com/sqlitebrowser/sqlitebrowser/issues/1548

**Comment by remram44** [comment]
Background on the problem: #211, my patch went in in May: https://github.com/sqlitebrowser/sqlitebrowser/pull/1349

**Comment by justinclift** [comment]
We finally got of the needed bits done, so the new release was made yesterday:

&nbsp; &nbsp; https://sqlitebrowser.org/blog/version-3-11-0-released/

**Comment by henrykironde** [comment]
New release solves this problem. Thanks to @remram44 and the folks at Sqlitebrowser.
