### ISSUE TITLE
SQL Aggregates and aliases record counts are incorrect

### ISSUE THREAD

**Issue by cla473** [datacarpentry/sql-ecology-lesson#252]
I am referfing to https://datacarpentry.org/sql-ecology-lesson/02-sql-aggregation/index.html

Under the 'What About NULL?' heading, the first paragraph states "From the last example, there should only be six records" .... there are only 5 records.  The third paragraph in this section also has 'six records'

I have looked at both the database provided, and imported the data from the csv files, and in both instances, the specified SQL only returns 5 records.

**Comment by remram44** [comment]
Ha, you are right! There are only 5 records, 3 of them non-null. The data must have changed. Thank you for reporting this!
