### ISSUE TITLE
SQL Aggregates and aliases - Key Points - incorrect Keyword - AVERAGE

### ISSUE THREAD

**Issue by cla473** [datacarpentry/sql-ecology-lesson#253]
This refers to:  https://datacarpentry.org/sql-ecology-lesson/02-sql-aggregation/index.html

The Key Points at the bottom of the page lists Functions like MIN, MAX, AVERAGE, SUM, COUNT.
AVERAGE does not work, and is not a valid function, it should be AVG.

**Comment by remram44** [comment]
Haha oops, good catch! Thanks for taking the time to let us know!
