### ISSUE TITLE
Not the same numbers on my computer (02-sql-aggregation)

### ISSUE THREAD

**Issue by MathildeMousset** [datacarpentry/sql-ecology-lesson#268]
After creating the summer_2000 view, when I execute the code on my computer, I obtain only five records where the text specify six. I have only three non null values (the text says there should be four). 

Not sure what is happening here. I downloaded the database again and copied-pasted the code directly from the course, but the result remains the same.

**Comment by ChristinaLK** [comment]
Thanks for reporting. A next step would be for someone to replicate this issue by running through the "Saving Queries for Future Use" section of the [aggregation episode](https://datacarpentry.org/sql-ecology-lesson/02-sql-aggregation/index.html) and seeing how many records they get from the final query of that section. 

I will try to get to this at some point, but other volunteers are welcome. :)

**Comment by ChristinaLK** [comment]
Reproduced, and someone else already changed the text (?).
