### ISSUE TITLE
Rewording of optionnal challenges (03-sql-joins)

### ISSUE THREAD

**Issue by MathildeMousset** [datacarpentry/sql-ecology-lesson#271]
1. Suggestion of rewording of optionnal challenge 2:
"How many specimens are there of each sex, and for each year?"

2. Need to add complementary info to challenge 2 and 3?
For the challenge 2, from the question, I don't understand why we filter the NULL out, since it is interesting to know how many individuals could not be sexed. Specify it in the question?
(similar holds for challenge 3)

**Comment by emjonaitis** [comment]
For issue 271 part 1, I don't think the suggested rewording represents the same question; I think to answer that question would require two separate queries.

For part 2, I agree with this. I think it's good to give people exercises where they specifically have to think about how to handle null values, but I also think the null values could be of substantive interest here. I'd suggest we split the difference for these exercises by asking them to retain the NULL values for optional challenge 2 and exclude them for optional challenge 3.

**Comment by ChristinaLK** [comment]
Closed by #276
