### ISSUE TITLE
Adjustment to wording in SQL Aggregation and Aliases Lesson

### ISSUE THREAD

**Issue by skk74** [datacarpentry/sql-ecology-lesson#284]
In the Aliases section the example with and without the AS keyword are not the same. I suggest adjusting the example with the AS keyword to read 

```
SELECT MAX(year) AS last_surveyed_year
FROM surveys AS surv;
```

**Comment by ChristinaLK** [comment]
Great point @skk74 . I'd even go a step farther and say that the example that doesn't include `AS` should use the same aliases: 
```
SELECT MAX(year) last_surveyed_year
FROM surveys surv;
```

**Comment by spbail** [comment]
I noticed that too, mind if I take this issue? (I'll go ahead and make a PR assuming that's ok :) )

**Comment by ChristinaLK** [comment]
@spbail no problem - thanks for submitting the PR!
