### ISSUE TITLE
search for just

### ISSUE THREAD

**Issue by ChristinaLK** [datacarpentry/sql-ecology-lesson#293]
Run over the lesson once looking for "just" and remove if appropriate.

**Comment by ltngo** [comment]
Hi! I removed the unnecessary uses of the word "just" (only showed up on two pages in the lesson) and submitted the pull requests as a part of my instructor checkout. Hope it's helpful!

**Comment by ChristinaLK** [comment]
Thanks @ltngo ! I don't see your changes yet - if you made them in your own fork of the repository, the final step is to submit your changes as a PR. 

If you go to your fork of the repository, you should see a "Pull request" option in the box above the list of files. If you click on that, it will compare your repo w/ the main one; you'll want to select the branches with your changes from the rightmost set of options. Once you have the correct branch selected, you should be able to submit a pull request by clicking on the "Create Pull Request" button. Let me know if you have any questions about this!

**Comment by ltngo** [comment]
Sorry, had a Friday afternoon brain lapse. I submitted the pull requests - hopefully you can see them now!

**Comment by ChristinaLK** [comment]
Yes! Will review and merge. Thanks again. :)
