### ISSUE TITLE
What is Sql (00-sql-introduction.md)

### ISSUE THREAD

**Issue by SebastianMosidi** [datacarpentry/sql-ecology-lesson#301]
What is SQL
SQL stands for Structured Query Language. SQL allows us to interact with relational databases through queries. These queries can allow you to perform a number of actions such as: insert, update and delete information in a database.

can we edit it to the following 

These queries can allow you to perform a number of actions such as: insert, select, update and delete information in a database.

**Comment by ChristinaLK** [comment]
Thanks for the suggestion @SebastianMosidi. That addition is helpful because it addresses the majority of what is covered in the lesson. 

I'll tag this issue as ready for a submission to the lesson.
