### ISSUE TITLE
Typo Found in Aggregating and Grouping Data Episode (checkout)

### ISSUE THREAD

**Issue by michaelshensky** [datacarpentry/sql-ecology-lesson#320]
In the third sentence of the last paragraph in the Aggregating and Grouping Data Episode (https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/_episodes/02-sql-aggregation.md) the word "querying" is currently misspelled as "quering" and should be fixed.

**Comment by aditya28sarin** [comment]
can you assign me this issue?

**Comment by ChristinaLK** [comment]
yes @aditya28sarin ! Done.

**Comment by adamancer** [comment]
Resolved in bb02293. Belated thank you to @aditya28sarin!
