### ISSUE TITLE
Link broken in Data Management with SQL ecology lesson, and wording suggestion

### ISSUE THREAD

**Issue by acsimonson** [datacarpentry/sql-ecology-lesson#321]
At the bottom of the setup page, under Am I Ready?, the link to the first episode is broken.

In that same section, there is the following phrase: If you can follow the instructions under “Relational Databases” or “Import”, everything should have downloaded and installed correctly.

Perhaps consider revising to something like: The instructions for importing the data into the DB Browser can be found under "Import."

**Comment by chbrandt** [comment]
I guess this issue can be closed @ChristinaLK

**Comment by jd-foster** [comment]
Thanks @chbrandt, looks like the link is working now. I agree the suggested phrase could be improved however.

**Comment by jd-foster** [comment]
Closed by #363.
