### ISSUE TITLE
00-sql-introduction Instructions to select tables in "Browse Data" tab

### ISSUE THREAD

**Issue by kekoziar** [datacarpentry/sql-ecology-lesson#332]
In 00-sql-introduction under the "Relational databases" section, it states 

> To see the contents of any table, click on it, and then click the “Browse Data” tab next to the “Database Structure” tab.

Except, that's not the functionality on my version of SQLite.  The table which opens when clicking in the "Browse Data" tab has no bearing on if you've selected a table in the "Database Structure" tab.  When first opened, the "Browse Data" tab will default to "Plots" (top table in list).  To select different tables, one needs to either right-click on the table in the "Database Structure" tab and select "Browse Table" from the menu, or click on the "Browse Data" tab and use the "Table:" drop-down menu on the top-left of that tab.  When clicking on "Browse Data" tab, it will be on the last selected table (or default to the top table).

**Comment by novica** [comment]
I can confirm the behavior as described by @kekoziar 
I tested on Linux 5.17.5 and Windows 10 with DB Browser for SQLite Version 3.12.2 on both.

**Comment by jd-foster** [comment]
Thanks @kekoziar for raising the issue and @novica for the PR to fix it.
