### ISSUE TITLE
Formatting messed up for bulleted list

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/sql-ecology-lesson#374]
### What is the problem?

In the [Database Design](https://datacarpentry.org/sql-ecology-lesson/discuss.html#proposed-episode-on-database-design) section, it looks like the sections "Naming conventions are important because" and "Names should adhere to certain standards" should have indented bulleted lists under them but this renders as paragraph text.  

### Location of problem (optional)

https://datacarpentry.org/sql-ecology-lesson/discuss.html#proposed-episode-on-database-design

**Comment by jd-foster** [comment]
Thanks for noticing. This is a proposed new episode and needs additional content along with a lot of editing to get it into a more readable state.
