### ISSUE TITLE
Advise on best option to install on Mac

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/sql-ecology-lesson#375]
### How could the content be improved?

In the [installation instructions](https://datacarpentry.org/sql-ecology-lesson/#software) we note there are several options for Windows installation and we make a recommendation for what should work for most people.  There are also two options for Mac installation but we don't make a recommendation there.  I don't use Macs often so I can not offer a recommendation.

**Comment by adamancer** [comment]
Hi @maneesha! Thanks for this contribution and the others that you submitted this week. I'll plan to review these next week and will let you know where they stand then.
