### ISSUE TITLE
On data import data emphasize types for the fields 

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/sql-ecology-lesson#49]
Feedback from a workshop. When learners import data, we do have in step 10 the data types that are supposed to be used, but it's easy to miss, so maybe we could restructure that a little. 

Also, for the import exercise, we don't tell students what the data types should be.

**Comment by apawlik** [comment]
+1 to adding notes on this in the materials and notes on how to change this once the DB is ready, and what impact that may have on the DB as well as on queries (for example ....WHERE year="1999"... vs WHERE year=1999....)

**Comment by fanie-riekert** [comment]
I am willing to work on this issue as part of my instructor training contribution.

**Comment by ashander** [comment]
can this be closed? (between #115 and notes on this in the guide https://github.com/datacarpentry/sql-ecology-lesson/blame/c3138e892504e041ea05021b6ddd851bb8bbd0c7/_extras/guide.md#L62 )

**Comment by tracykteal** [comment]
Thanks, resolved as noted by @ashander
