### ISSUE TITLE
Add comment to instructor notes referring back to messy spreadsheet

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/sql-ecology-lesson#50]
To create the link between the importance of structured data and being able to use SQL, add to the instructors notes that this link should be pointed out. 

e.g. "Remember that messy spreadsheet? What would have happened if we tried to load that in to SQL?"

Linked to https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/6

**Comment by ethanwhite** [comment]
This is an awesome idea!

**Comment by kcranston** [comment]
[Done](https://github.com/datacarpentry/sql-ecology-lesson/commit/beb89b596df2ba56e79b4be23e13a5c0dcfa9753).
