### ISSUE TITLE
kramdown rendering

### ISSUE THREAD

**Issue by tpoisot** [datacarpentry/sql-ecology-lesson#79]
Is it safe to just remove `markdown` from the `_config.yml` in anticipation for the May 1st deprecation of `redcarpet` in profit of `kramdown`?

Pinging @datacarpentry/coordinators and @datacarpentry/maintainers too, maybe this is being discussed in issues on another repo.

**Comment by fmichonneau** [comment]
I believe it's safe in general and especially for the SQL lesson as there
is no highlighting.

**Comment by tracykteal** [comment]
Yes, please do. We need to roll out that change on all of the lessons and confirm that things will still work fine.

**Comment by tpoisot** [comment]
Allright, chaning now.

Closes #79 .
