### ISSUE TITLE
Improvements to the JOINS section

### ISSUE THREAD

**Issue by sschmeier** [datacarpentry/sql-ecology-lesson#81]
1.
I think it would be a good idea to start the "Joins and aliases" section with an example of what happens if we do a JOIN but do not use an ON, as this is not a necessity. Basically explaining that this will lead to a joining of all rows of one table to all rows of the other table. Then explaining why we don't want this, e.g. big tables=lots of calculations = lots of time, finally explaining that we want to join tables based on common entries in two or more tables using ON. Here we also might want to mention briefly, that this relates back to database design and table structure, as we can only join tables that have common table/column entries. So we need to think about how to design the DB upfront.

2.
We should mention that 
"ON surveys.species_id = species.species_id" and "USING (species_id)" 
will not get the same result, as the "species_id" column in the later will only appear once.

Seb

**Comment by tpoisot** [comment]
**1** - I don't think it's wise to spend time saying "Hey, so we can do so and so", to basically conclude with "By the way, this is not what we want at all". I would indicate in a single sentence that `ON` is not a necessity but results in gigantic tables, so we use it. And I also don't think we have to do in the details of *why* it works. @orchid00 , your input? 

On the other hand, yes, the part about *designing* the DB is very important. In a way, this relates to #45 and #49, and maybe will have to be part of additional material. This lesson is (currently) about using an existing DB, but I'd like to see it cover DB design in the future.

**2** - absolutely. Please go ahead and submit a PR.

**Comment by orchid00** [comment]
Thanks @tpoisot and @sschmeier, I agree with you both about starting JOIN with a simple example (without filtering aka using ON). When I taught this part in SC, I made clear: JOIN creates the cross product of two tables and give and example (with two small tables) that joins combines each record of one table with each record of the other table, to give all possible combinations. But because this is rarely useful we use ON to select those records that we are interested on, based on a "key" field. Then a bit of explaining what a key field would be. I said think about your insurance number and then how with this number the insurance company knows all about you. 

@tpoisot Was that what you were looking for?

**Comment by tpoisot** [comment]
@orchid00 -- yes. I think your reply is a good game plan about what to put in a PR.

**Comment by waveform80** [comment]
As the resident pedant, I'd also add that the condition is not optional (and this is implemented in several engines including postgres); in the standard ON or USING are mandatory in INNER and OUTER JOIN, while no condition can be specified for CROSS or NATURAL JOIN.

However, I take the point that without a condition there's no reason a join shouldn't represent a cartesian product (the standard probably mandates this syntax as a safe-guard against people accidentally performing unintended cartesian products by forgetting the condition - i.e. to get people to specify CROSS explicitly if they *really* want one), and that it's a potentially useful stepping stone in teaching joins given that the preferred engine (SQLite) does permit such syntax.

**Comment by orchid00** [comment]
So, after @waveform80 thoughtful conclusions, can we close this issue? @tpoisot

**Comment by tpoisot** [comment]
Yes. Closes #81
