### ISSUE TITLE
From legacy Access to SQLite

### ISSUE THREAD

**Issue by jsta** [datacarpentry/sql-ecology-lesson#84]
In #45, @tpoisot suggests the idea of a "From Excel to SQL" capstone module.  A related idea might be best practices for going "From legacy Access to SQLite". Is this beyond the scope of this lesson or does this sort of thing already exist elsewhere?

**Comment by orchid00** [comment]
This might be out of the scope. But just of curiosity do you already have a module which will be easily implemented?

**Comment by jsta** [comment]
I totally understand. I have no module but I am currently using [mdb-tools](https://github.com/brianb/mdbtools) for this purpose. I wonder if a note about Access is warranted. Maybe in the lesson into?

**Comment by tpoisot** [comment]
We could *maybe* have diff. capstones with conversion. @tracykteal ?

I know several people that use Access, so it would probably help them.
