### ISSUE TITLE
Improve challenge?

### ISSUE THREAD

**Issue by tpoisot** [datacarpentry/sql-ecology-lesson#85]
@fmichonneau -- you are the last one to edit this challenge

https://github.com/datacarpentry/sql-ecology-lesson/blame/gh-pages/02-sql-aggregation.md#L35

What is the solution supposed to be?

**Comment by waveform80** [comment]
I'm afraid @fmichonneau only added an "a" to that particular challenge in commit 940a4bd0576c6104a58235212f7dd5b4428a2ad7 - it looks like @apawlik is the originator of the challenge.

 I'd suggest the solution to the first part is simply:

```sql
SELECT
    SUM(weight),
    AVG(weight),
    MIN(weight),
    MAX(weight)
FROM
    surveys
```

The second part is harder and to be honest I'm not sure how I'd solve it given only the elements taught in the lesson to that point. How I'd solve it given no restrictions would be to simply construct a relation containing the required weight ranges, and join surveys to that, aggregating the result as before but grouping it by the weight-range (formatted appropriately):

```sql
WITH weight_ranges(lower_bound, upper_bound) AS (
    VALUES
        (0, 10),
        (10, 20),
        (20, 30),
        (30, 40),
        (40, 50),
        (50, 60),
        (60, 70),
        (70, NULL)
)
SELECT
    CAST(COALESCE(r.lower_bound, 'unbounded') AS VARCHAR)
        || ' to ' ||
        CAST(COALESCE(r.upper_bound, 'unbounded') AS VARCHAR) AS range,
    SUM(s.weight),
    AVG(s.weight),
    MIN(s.weight),
    MAX(s.weight)
FROM
    surveys s
    JOIN weight_ranges r
        ON s.weight >= r.lower_bound
        AND (s.weight < r.upper_bound OR r.upper_bound IS NULL)
GROUP BY
    r.lower_bound,
    r.upper_bound
```

However, at that point in the course `JOIN` hasn't been covered (and construction of arbitrary relations with `VALUES` isn't covered at all, let alone use of sub-queries either involving `WITH` or in the `FROM` clause directly). If the challenge allows construction of new tables to solve it (and assuming we've made a table called weight_ranges), then the solution simply becomes:

```sql
SELECT
    CAST(COALESCE(r.lower_bound, 'unbounded') AS VARCHAR)
        || ' to ' ||
        CAST(COALESCE(r.upper_bound, 'unbounded') AS VARCHAR) AS range,
    SUM(s.weight),
    AVG(s.weight),
    MIN(s.weight),
    MAX(s.weight)
FROM
    surveys s
    JOIN weight_ranges r
        ON s.weight >= r.lower_bound
        AND (s.weight < r.upper_bound OR r.upper_bound IS NULL)
GROUP BY
    r.lower_bound,
    r.upper_bound
```

Although that still doesn't resolve the fact that JOIN hasn't been covered at that point.

**Comment by fmichonneau** [comment]
Hi @tpoisot 

I can confirm that I didn't create this challenge :)

When I taught this, I understood this challenge simply as something like:

```sql
SELECT
    SUM(weight),
    AVG(weight),
    MIN(weight),
    MAX(weight)
FROM
    surveys
WHERE
     weight > 10 AND weight <= 50
```

**Comment by tpoisot** [comment]
Allright, so I'll suggest an edit to make it clearer.
