### ISSUE TITLE
committing directly to gh-pages, oops

### ISSUE THREAD

**Issue by kcranston** [datacarpentry/sql-ecology-lesson#86]
In preparation for a workshop at [UNC](http://kcranston.github.io/2016-04-11-UNC/), I made several commits directly to gh-pages (checked with @ethanwhite who said "go ahead!' and then, "oops! I am no longer the maintainer). Note that none of them affect the lesson directly, only adding / editing instructor notes and also the lesson documentation (specifically, updating the maintainers)

Let me know if you are ok with these changes, or if you want me to revert and PR. @tpoisot @orchid00

**Comment by orchid00** [comment]
I've checked your changes and I think it's all good, plus you closed some issues which is good too. I just added a new comment on one of the pages "add tip about wrong data type".

**Comment by tpoisot** [comment]
I second @orchid00 -- thanks for the changes @kcranston !
