### ISSUE TITLE
Numeric `IN` queries

### ISSUE THREAD

**Issue by jsta** [datacarpentry/sql-ecology-lesson#88]
I was working through the `Basic queries` lesson and I got stuck for a moment when trying to use numeric arguments to the `IN` keyword. Up until this point all the numeric queries are unquoted. However, I believe they need to be quoted when used with `IN`. Submitting a PR shortly with an example query.

**Comment by waveform80** [comment]
Sorry - numeric queries definitely don't require quotes. It probably won't harm in SQLite (which treats more or less everything as a string) but it'd fail completely in any other engine. For that matter, it'd also fail in SQLite under certain circumstances (leading zeros, other extraneous formatting, etc). Whatever issue you had with the numeric arguments to IN is something other than missing quotes.

**Comment by jsta** [comment]
No worries. My mistake. It was a misspecified data type (numeric classified as text). Hopefully the closed issue will alert others.
