### ISSUE TITLE
Species not a variable - use species_id

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/sql-ecology-lesson#96]
Received via email: 

FYI: In the section below, there is a typo. In the CHALLENGE, you are asked to query species. There is no species in the surveys table. You must use species_id.

Sorting
We can also sort the results of our queries by using ORDER BY. For simplicity, let’s go back to the species table and alphabetize it by taxa.

SELECT *
FROM species
ORDER BY taxa ASC;
The keyword ASC tells us to order it in Ascending order. We could alternately use DESC to get descending order.

SELECT *
FROM species
ORDER BY taxa DESC;
ASC is the default.

We can also sort on several fields at once. To truly be alphabetical, we might want to order by genus then species.

SELECT *
FROM species
ORDER BY genus ASC, species ASC;

Challenge
Write a query that returns year, species, and weight in kg from the surveys table, sorted with the largest weights at the top.

**Comment by tpoisot** [comment]
Looks :+1:  Can you submit this as a PR?

**Comment by ErinBecker** [comment]
@tpoisot I'm not a SQL user. If this is really just as simple as changing "species" to "species_id" every time it appears in the exercises, I can do this. Just no way for me to test (without actually learning SQL - which I should do eventually!), so a bit nervous about making changes myself.

**Comment by tpoisot** [comment]
Right, so can you ask whoever sent that through email to submit as a PR? If not, I'll do it, but it's always better when there is a PR to accompany possible changes.

**Comment by ErinBecker** [comment]
Agreed that having a PR would be ideal, but since we don't require DC community members to know Git, I'm going to say we go ahead and make the changes without asking this user to submit a PR. My general assumption is that someone submitting an issue by email like this likely isn't comfortable with Git, and we should accommodate that.

**Comment by tpoisot** [comment]
Sure -- will get around to fix later.

**Comment by tracykteal** [comment]
'species' is a table in this database. And in that table are the columns 'species' which is the full species name, and 'species_id' which is the ID of the species that is also used in the 'surveys' table.

So, this isn't a typo and the query works as it is.

It is confusing though about the 'species' table and then various column names that are the same or similar. We tried some clarification with 'species_id', but instructors do need to be clear here that we've switched over to working with the 'species' table rather than the 'surveys' table they had been working with. I'll put in a PR to address this.

**Comment by tracykteal** [comment]
PR https://github.com/datacarpentry/sql-ecology-lesson/pull/97

**Comment by ethanwhite** [comment]
> So, this isn't a typo and the query works as it is.

I think original comment is about the challenge, which does use `species` where it should use `species_id`.

**Comment by tpoisot** [comment]
I merged the updated PR.
